[package]
name = "testing_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
anyhow = "1.0.75"
bincode = "2.0.0-rc.3"
models_hf = { path = "../models_hf" }
